package main;

import javax.swing.*;
import java.awt.*;
import java.util.Arrays;
import java.util.List;
import Sach.BookManagerPanel;
import DocGia.ReaderManagerPanel;
import MuonTra.BorrowingManagerPanel;
import NhanVien.StaffManagerPanel;
import TheLoai.CategoryManagerPanel;
import NXB.PublisherManagerPanel;
import TacGia.AuthorManagerPanel;
import ThongKe.StatisticsPanel;

public class LibraryManagerUI extends javax.swing.JPanel implements java.beans.Customizer {
    
    private Object bean;
    private final List<String> projectSections = Arrays.asList(
            "Quản lý Sách",
            "Quản lý Độc giả",
            "Quản lý Mượn/Trả",
            "Quản lý Nhân viên",
            "Quản lý Danh mục",
            "Quản lý Nhà xuất bản",
            "Quản lý Tác giả",
            "Thống kê/Báo cáo"
    );
    private ChatAssistantDialog chatDialog;

    public LibraryManagerUI() {
        initComponents();
        setupTabbedPane();
        setupChatButton();
    }
    
    public void setObject(Object bean) {
        this.bean = bean;
    }

    private void setupTabbedPane() {
        setLayout(new BorderLayout());
        JTabbedPane tabbedPane = new JTabbedPane();

        tabbedPane.addTab("Quản lý Sách", new BookManagerPanel());
        tabbedPane.addTab("Quản lý Độc giả", new ReaderManagerPanel());
        tabbedPane.addTab("Quản lý Mượn/Trả", new BorrowingManagerPanel());
        tabbedPane.addTab("Quản lý Nhân viên", new StaffManagerPanel());
        tabbedPane.addTab("Quản lý Danh mục", new CategoryManagerPanel());
        tabbedPane.addTab("Quản lý Nhà xuất bản", new PublisherManagerPanel());
        tabbedPane.addTab("Quản lý Tác giả", new AuthorManagerPanel());
        tabbedPane.addTab("Thống kê/Báo cáo", new StatisticsPanel());

        add(tabbedPane, BorderLayout.CENTER);
    }

    private void setupChatButton() {
        JButton chatButton = new JButton("Mở chat hỗ trợ");
        chatButton.addActionListener(e -> openChatAssistant());

        JPanel bottomPanel = new JPanel(new FlowLayout(FlowLayout.RIGHT));
        bottomPanel.add(chatButton);

        add(bottomPanel, BorderLayout.SOUTH);
    }

    private void openChatAssistant() {
        if (chatDialog == null || !chatDialog.isDisplayable()) {
            Window owner = SwingUtilities.getWindowAncestor(this);
            chatDialog = new ChatAssistantDialog(owner, projectSections);
        }
        chatDialog.setVisible(true);
        chatDialog.toFront();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the FormEditor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        setLayout(new java.awt.BorderLayout());
}// </editor-fold>                        


    // Variables declaration - do not modify                     
    // End of variables declaration                   

    public static void main(String[] args) {
        SwingUtilities.invokeLater(() -> {
            JFrame frame = new JFrame("Quản lý Thư viện");
            frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
            frame.setSize(1000, 700); 
            frame.setLocationRelativeTo(null);
            frame.setContentPane(new LibraryManagerUI());
            frame.setVisible(true);
        });
    }
}
