package main;

import javax.swing.*;
import java.awt.*;
import Sach.BookManagerPanel;
import DocGia.ReaderManagerPanel;
import MuonTra.BorrowingManagerPanel;
import NhanVien.StaffManagerPanel;
import TheLoai.CategoryManagerPanel;
import NXB.PublisherManagerPanel;
import TacGia.AuthorManagerPanel;
import ThongKe.StatisticsPanel;

public class LibraryManagerUI extends javax.swing.JPanel implements java.beans.Customizer {
    
    private Object bean;

    public LibraryManagerUI() {
        initComponents();
        setupTabbedPane();
    }
    
    public void setObject(Object bean) {
        this.bean = bean;
    }

    private void setupTabbedPane() {
        setLayout(new BorderLayout());
        JTabbedPane tabbedPane = new JTabbedPane();

        tabbedPane.addTab("Quản lý Sách", new BookManagerPanel());
        tabbedPane.addTab("Quản lý Độc giả", new ReaderManagerPanel());
        tabbedPane.addTab("Quản lý Mượn/Trả", new BorrowingManagerPanel());
        tabbedPane.addTab("Quản lý Nhân viên", new StaffManagerPanel());
        tabbedPane.addTab("Quản lý Danh mục", new CategoryManagerPanel());
        tabbedPane.addTab("Quản lý Nhà xuất bản", new PublisherManagerPanel());
        tabbedPane.addTab("Quản lý Tác giả", new AuthorManagerPanel());
        tabbedPane.addTab("Thống kê/Báo cáo", new StatisticsPanel());

        add(tabbedPane, BorderLayout.CENTER);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the FormEditor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setLayout(new java.awt.BorderLayout());
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

    public static void main(String[] args) {
        SwingUtilities.invokeLater(() -> {
            JFrame frame = new JFrame("Quản lý Thư viện");
            frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
            frame.setSize(1000, 700); 
            frame.setLocationRelativeTo(null);
            frame.setContentPane(new LibraryManagerUI());
            frame.setVisible(true);
        });
    }
}
